### ISSUE TITLE
Fatal error: Class 'Zend_XmlRpc_Value_Base64' not found

### ISSUE THREAD

**Issue by m9iqbal** [eMagicOne/MagentoStoreManagerConnector#8]
As per [Magento DevDocs](https://devdocs.magento.com/guides/v2.3/release-notes/backward-incompatible-changes/), Zend_XmlRpc is no longer supported with the release of 2.3.0.

When I run `bin/magento setup:di:compile`, I get `Fatal error: Class 'Zend_XmlRpc_Value_Base64' not found in /vendor/emagicone/module-bridgeconnector/Helper/Base64Helper.php on line 25`.

It's because of the fact that `Emagicone\Bridgeconnector\Helper\Base64Helper` is still extending `Zend_XmlRpc_Value_Base64`. Has there been any update since 2.3.0?

**Comment by eMagicOne** [comment]
Hello! 
Thank you for your comment.
Indeeed, we have changed the connector module, so it could be compatible with Magento 2.3.
Though, Store Manager itself will support Magento 2.3. in a few days with the new release.
You are welcome to contact our support at the official website and we will keep you updated when new version will be available and send the corresponding connector.

**Comment by volanar** [comment]
The module is still not working. Error not resolve

**Comment by eMagicOne** [comment]
Hello!
Thank you for your comment.
We are currently working on this issue, it is on the stage of testing.
You are also welcome to submit a ticket on our official website to be notified when the compatible version will be available.

**Comment by frosit** [comment]
Any news on when this will be resolved? Your support staff provided me with a beta for 2.3 but I can't continue because of this issue. If it will take weeks I will start working on a fix myself.

**Comment by eMagicOne** [comment]
Hello!
Thank you for your comment.
The new version of Store Manager (3.24) and Bridge Connector compatible with Magento 2.3 is available for download on our official website in Changelog section
Alternatively, you may contact our support directly and they will provide you with the module.

**Comment by miro91** [comment]
@eMagicOne where I can find the latest version because on the marketplace 1.0.6 is still using the \ Zend_XmlRpc_Value_Base64 class.
Can you please send some links for download working version for 2.3.0 +
I am trying to upgrade my Magento to 2.3.2

**Comment by eMagicOne** [comment]
Hello!
Thank you for your comment.
To download the module, please go to our official webpage in the Change log section. 
You may also contact our support and our manager will provide you with the module.

**Comment by miro91** [comment]
@eMagicOne Please send direct link because I can't find it. There is no change log section that I can find.

**Comment by eMagicOne** [comment]
Hello!
Thank you for your message.
Please, go to Support dropdown -> Changelog -> Magento Store Manager Connector Manual.
Also, you can contact us via Live Chat on our official website (find the icon in the right lower corner), and we will provide you with the module instantly.

**Comment by eMagicOne** [comment]
Current issue has been corrected in the renewed Store Manager Connector that can be downloaded by the [link](https://marketplace.magento.com/emagicone-module-connector.html).

**Comment by jimmyg423** [comment]
Hi,
We have Magento 2.3.1 installed and v1.0.7 of the Bridgeconnector installed and still seeing the error: Fatal error:  Class 'Zend_XmlRpc_Value_Base64' not found

**Comment by eMagicOne** [comment]
Hello,
thank you for your comment.
There are two separate modules for shopping carts v.2.2x and 2.3.x.
You need to [install Bridge Connector v.1.0.4](https://marketplace.magento.com/emagicone-module-connector.html) to solve the issue.

**Comment by loekvangool** [comment]
I am getting this error with Bridge Connector 1.0.7 @eMagicOne

**Comment by eMagicOne** [comment]
Hello @loekvangool,
Thank you for your comment.
If you are working with Magento 2.3, you need corresponding connector to it (there are two of them - one for Magento up to 2.2 (v.1.0.7) and the other starting from 2.3 (v.1.0.4)). 
You can download the module for Magento 2.3 [here.](https://marketplace.magento.com/emagicone-module-connector.html)

**Comment by loekvangool** [comment]
@eMagicOne how can the 2.3 module be installed using Composer?

**Comment by eMagicOne** [comment]
@loekvangool  You can install it the same way as any other extension, kindly use [this guide](https://store-manager-for-magento-doc.emagicone.com/quick-start-guide/1-5-magento-store-manager-connector/Install-connector-for-magento-2-3-and-above).

**Comment by loekvangool** [comment]
@eMagicOne just now I did a `composer info` and I found that 1.0.7 was installed on Magento 2.3.x, having never had a <2.3.0 Magento install (so it was clean). At some point, `composer require emagicone/module-connector` must have pointed at 1.0.7?

```
emagicone/module-bridgeconnector                                  1.0.7
```

I did:

```
composer remove emagicone/module-connector
composer require emagicone/module-connector
php bin/magento setup:di:compile;
```

Which installed 1.0.4 and did a successful recompile.

**Comment by eMagicOne** [comment]
@loekvangool Have you updated your Magento to 2.3 recently?

**Comment by loekvangool** [comment]
I've done a clean install of 2.3.x recently, and have done a couple of `composer update` commands in the meantime, but have never ran Magento 2.2 or older.

**Comment by eMagicOne** [comment]
Can you please contact our support via the email contact@emagicone.com with the detailed actions you've made before you faced the issue with v.1.0.7? We'll gladly check your request to find out the reason of this inconvenience. 
Waiting for your email.
